# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/librodigital_auth
spring.datasource.username=postgres
spring.datasource.password=monsalve1974
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
# Logs SQL (solo desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Nombre del servicio
spring.application.name=authService
# Puerto
server.port=8091
# Logs (mejor visibilidad)
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

jwt.secret=librodigital2026SecretKeyForJWTTokenGenerationAndValidation12345


